/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_api_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Orders
         * @description 反射の回折次数ごとの角度分布を返す。平面多層膜では 0 次（正反射）のみ。
         */
        post: operations["simulate_orders_api_simulate_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate/sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Sweep
         * @description 入射角スイープ。角度ごとの R/T スペクトルと(任意で)反射色を返す。
         */
        post: operations["simulate_sweep_api_simulate_sweep_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AngularDistributionDTO
         * @description 1 波長の角度分布。orders は出射角の昇順（伝搬する次数のみ）。
         */
        AngularDistributionDTO: {
            /** Wavelengthnm */
            wavelengthNm: number;
            /** Orders */
            orders: components["schemas"]["DiffractionOrderDTO"][];
        };
        /** ColorDTO */
        ColorDTO: {
            /** R */
            r: number;
            /** G */
            g: number;
            /** B */
            b: number;
            /** Hex */
            hex: string;
        };
        /**
         * DiffractionOrderDTO
         * @description 1 つの回折次数への反射パワーの配分。
         */
        DiffractionOrderDTO: {
            /** Order */
            order: number;
            /** Angledeg */
            angleDeg: number;
            /** Reflectance */
            reflectance: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LayerDTO */
        LayerDTO: {
            /** Name */
            name: string;
            /** Thicknessnm */
            thicknessNm: number;
            /** N */
            n: number;
            /**
             * K
             * @default 0
             */
            k: number;
            /**
             * Regions
             * @default []
             */
            regions: components["schemas"]["RegionDTO"][];
        };
        /** OrdersResponse */
        OrdersResponse: {
            /** Distributions */
            distributions: components["schemas"]["AngularDistributionDTO"][];
        };
        /**
         * Polarization
         * @description 偏光。S=TE、P=TM。
         * @enum {string}
         */
        Polarization: "s" | "p";
        /**
         * RegionDTO
         * @description 層内の矩形領域（面内パターン）。単位胞左端を 0 とする nm 座標。
         */
        RegionDTO: {
            /** Xnm */
            xNm: number;
            /** Widthnm */
            widthNm: number;
            /** N */
            n: number;
            /**
             * K
             * @default 0
             */
            k: number;
        };
        /** SimulationRequest */
        SimulationRequest: {
            /** Wlmin */
            wlMin: number;
            /** Wlmax */
            wlMax: number;
            /** Wlpoints */
            wlPoints: number;
            /**
             * Thetadeg
             * @default 0
             */
            thetaDeg: number;
            /** @default s */
            pol: components["schemas"]["Polarization"];
            /** Layers */
            layers: components["schemas"]["LayerDTO"][];
            /** Periodnm */
            periodNm?: number | null;
            /**
             * Numbasis
             * @default 1
             */
            numBasis: number;
            /** Wavelengthsnm */
            wavelengthsNm?: number[] | null;
        };
        /** SimulationResponse */
        SimulationResponse: {
            /** Wavelengths */
            wavelengths: number[];
            /** R */
            R: number[];
            /** T */
            T: number[];
            reflectedColor: components["schemas"]["ColorDTO"];
        };
        /**
         * SweepEntryDTO
         * @description 1 入射角分の結果。キーは SimulationResponse に合わせて R / T。
         */
        SweepEntryDTO: {
            /** Thetadeg */
            thetaDeg: number;
            /** R */
            R: number[];
            /** T */
            T: number[];
            color?: components["schemas"]["ColorDTO"] | null;
        };
        /**
         * SweepRequest
         * @description 入射角スイープのリクエスト。theta_deg の代わりに theta_degs を掃引する。
         */
        SweepRequest: {
            /** Wlmin */
            wlMin: number;
            /** Wlmax */
            wlMax: number;
            /** Wlpoints */
            wlPoints: number;
            /**
             * Thetadeg
             * @default 0
             */
            thetaDeg: number;
            /** @default s */
            pol: components["schemas"]["Polarization"];
            /** Layers */
            layers: components["schemas"]["LayerDTO"][];
            /** Periodnm */
            periodNm?: number | null;
            /**
             * Numbasis
             * @default 1
             */
            numBasis: number;
            /** Wavelengthsnm */
            wavelengthsNm?: number[] | null;
            /** Thetadegs */
            thetaDegs: number[];
            /**
             * Includecolors
             * @default true
             */
            includeColors: boolean;
        };
        /** SweepResponse */
        SweepResponse: {
            /** Wavelengths */
            wavelengths: number[];
            /** Entries */
            entries: components["schemas"]["SweepEntryDTO"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    simulate_api_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_orders_api_simulate_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_sweep_api_simulate_sweep_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SweepRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SweepResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
