/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_api_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Orders
         * @description 反射の回折次数ごとの角度分布を返す。平面多層膜では 0 次（正反射）のみ。
         */
        post: operations["simulate_orders_api_simulate_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate/sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Sweep
         * @description 入射角スイープ。角度ごとの R/T スペクトルと(任意で)反射色を返す。
         */
        post: operations["simulate_sweep_api_simulate_sweep_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Materials */
        get: operations["list_materials_api_materials_get"];
        put?: never;
        /** Create Material */
        post: operations["create_material_api_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Material */
        get: operations["get_material_api_materials__material_id__get"];
        put?: never;
        post?: never;
        /** Delete Material */
        delete: operations["delete_material_api_materials__material_id__delete"];
        options?: never;
        head?: never;
        /** Rename Material */
        patch: operations["rename_material_api_materials__material_id__patch"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AngularDistributionDTO
         * @description 1 波長の角度分布。orders は出射角の昇順（伝搬する次数のみ）。
         */
        AngularDistributionDTO: {
            /** Wavelengthnm */
            wavelengthNm: number;
            /** Orders */
            orders: components["schemas"]["DiffractionOrderDTO"][];
        };
        /** ColorDTO */
        ColorDTO: {
            /** R */
            r: number;
            /** G */
            g: number;
            /** B */
            b: number;
            /** Hex */
            hex: string;
        };
        /**
         * DiffractionModeDTO
         * @description 回折次数で分けた 1 つの見方（0 次以外 or 全次数）のスペクトルと色。
         */
        DiffractionModeDTO: {
            /** R */
            R: number[];
            color?: components["schemas"]["ColorDTO"] | null;
        };
        /**
         * DiffractionModesDTO
         * @description 反射率を回折次数で分けたもの。0 次（正反射）は親の R / color。
         *
         *     non_zeroth は m ≠ 0 の合計（正反射以外の方向へ散った回折光）、total は
         *     全次数の合計。別方向へ出る光の足し算なので R = total − non_zeroth が成り立つ。
         *     平面多層膜には m ≠ 0 が無いので non_zeroth は 0、total は R に一致する。
         */
        DiffractionModesDTO: {
            nonZeroth: components["schemas"]["DiffractionModeDTO"];
            total: components["schemas"]["DiffractionModeDTO"];
        };
        /**
         * DiffractionOrderDTO
         * @description 1 つの回折次数への反射パワーの配分。
         */
        DiffractionOrderDTO: {
            /** Order */
            order: number;
            /** Angledeg */
            angleDeg: number;
            /** Reflectance */
            reflectance: number;
        };
        /** DispersionPointDTO */
        DispersionPointDTO: {
            /** Wavelengthnm */
            wavelengthNm: number;
            /** N */
            n: number;
            /** K */
            k: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LayerDTO */
        LayerDTO: {
            /** Name */
            name: string;
            /** Thicknessnm */
            thicknessNm: number;
            /** N */
            n: number;
            /**
             * K
             * @default 0
             */
            k: number;
            /**
             * Regions
             * @default []
             */
            regions: components["schemas"]["RegionDTO"][];
        };
        /**
         * MaterialCreateRequest
         * @description 材料の登録。content はファイルの中身の文字列（読み取りはバックエンドで行う）。
         */
        MaterialCreateRequest: {
            /** Name */
            name: string;
            /** Content */
            content: string;
        };
        /**
         * MaterialDTO
         * @description 詳細用。n, k の表を含む（グラフ表示に使う）。
         */
        MaterialDTO: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Points */
            points: components["schemas"]["DispersionPointDTO"][];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** MaterialRenameRequest */
        MaterialRenameRequest: {
            /** Name */
            name: string;
        };
        /**
         * MaterialSummaryDTO
         * @description 一覧用。層の材料選択に必要なのは id と名前だけ。
         */
        MaterialSummaryDTO: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
        };
        /** OrdersResponse */
        OrdersResponse: {
            /** Distributions */
            distributions: components["schemas"]["AngularDistributionDTO"][];
        };
        /**
         * Polarization
         * @description 偏光。S=TE、P=TM。
         * @enum {string}
         */
        Polarization: "s" | "p";
        /**
         * RegionDTO
         * @description 層内の矩形領域（面内パターン）。単位胞左端を 0 とする nm 座標。
         */
        RegionDTO: {
            /** Xnm */
            xNm: number;
            /** Widthnm */
            widthNm: number;
            /** N */
            n: number;
            /**
             * K
             * @default 0
             */
            k: number;
        };
        /** SimulationRequest */
        SimulationRequest: {
            /** Wlmin */
            wlMin: number;
            /** Wlmax */
            wlMax: number;
            /** Wlpoints */
            wlPoints: number;
            /**
             * Thetadeg
             * @default 0
             */
            thetaDeg: number;
            /** @default s */
            pol: components["schemas"]["Polarization"];
            /** Layers */
            layers: components["schemas"]["LayerDTO"][];
            /** Periodnm */
            periodNm?: number | null;
            /**
             * Numbasis
             * @default 1
             */
            numBasis: number;
            /** Wavelengthsnm */
            wavelengthsNm?: number[] | null;
        };
        /** SimulationResponse */
        SimulationResponse: {
            /** Wavelengths */
            wavelengths: number[];
            /** R */
            R: number[];
            /** T */
            T: number[];
            reflectedColor: components["schemas"]["ColorDTO"];
            diffraction?: components["schemas"]["DiffractionModesDTO"] | null;
        };
        /**
         * SweepEntryDTO
         * @description 1 入射角分の結果。キーは SimulationResponse に合わせて R / T。
         */
        SweepEntryDTO: {
            /** Thetadeg */
            thetaDeg: number;
            /** R */
            R: number[];
            /** T */
            T: number[];
            color?: components["schemas"]["ColorDTO"] | null;
            diffraction?: components["schemas"]["DiffractionModesDTO"] | null;
        };
        /**
         * SweepRequest
         * @description 入射角スイープのリクエスト。theta_deg の代わりに theta_degs を掃引する。
         */
        SweepRequest: {
            /** Wlmin */
            wlMin: number;
            /** Wlmax */
            wlMax: number;
            /** Wlpoints */
            wlPoints: number;
            /**
             * Thetadeg
             * @default 0
             */
            thetaDeg: number;
            /** @default s */
            pol: components["schemas"]["Polarization"];
            /** Layers */
            layers: components["schemas"]["LayerDTO"][];
            /** Periodnm */
            periodNm?: number | null;
            /**
             * Numbasis
             * @default 1
             */
            numBasis: number;
            /** Wavelengthsnm */
            wavelengthsNm?: number[] | null;
            /** Thetadegs */
            thetaDegs: number[];
            /**
             * Includecolors
             * @default true
             */
            includeColors: boolean;
        };
        /** SweepResponse */
        SweepResponse: {
            /** Wavelengths */
            wavelengths: number[];
            /** Entries */
            entries: components["schemas"]["SweepEntryDTO"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    simulate_api_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_orders_api_simulate_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_sweep_api_simulate_sweep_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SweepRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SweepResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_materials_api_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialSummaryDTO"][];
                };
            };
        };
    };
    create_material_api_materials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_api_materials__material_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_material_api_materials__material_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_material_api_materials__material_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialSummaryDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
